devnet-0: genesis.blob: third time's the charm
I was encountering the following error loading `genesis.blob` when
it was generated using the `testnet` branch of Libra:

    panicked at 'failed to load genesis transaction!:
    Custom("The Address [] is of invalid length")

@naolduga pointed out this commit which changes the account address wire
serialization as a potential culprit:

https://github.com/libra/libra/commit/b5901bcd9d78fe1d14a6d64067aadca2e20c0cdd

To work around that, I've attempted to generate genesis.blob using Libra
as of that commit's parent:

https://github.com/libra/libra/commit/667344248287a1647f42a793e92414853a5fa335

For me at least, it's loading and the node is starting.